### ISSUE TITLE
moonboard app doesn´t send anything to led

### ISSUE THREAD

**Issue by smai86** [lidiapb/moonboard#5] opened 2021-05-20 15:44 UTC
Hello,

got the problem that my iphone 5 wont send any signal to the LEDs. 
Im using a pi zero with fresh installed os...

Any Ideas?

Thanks!
Steffen

**Comment by smai86** [comment] 2021-05-20 18:26
EDIT: Tried with an old Huawei (Android 6) works perfect...

but why iphone not?!

**Comment by reinarrow** [comment] 2021-06-19 08:46
Hi @smai86. Have you looked at the issue #4?

I was having the same problem with iPhone, and modifying the bluetooth.service to disable the battery plugin from bluez did the trick. Seems that they introduced some change in that update that broke the iPhone compatibility. I hope it helps.

**Comment by reinarrow** [comment] 2021-06-19 09:01
Closing as duplicate of #4. Please continue discussion in there.

**Closed as completed by reinarrow** 2021-06-19 09:01 UTC
